{
    'name': 'Chấm công',
    'version': '1.0',
    'summary': 'Module quản lý chấm công',
    'sequence': 10,
    'description': """Module quản lý chấm công""",
    'category': 'Human Resources',
    'author': 'Nhóm 10',
    'website': '',
    'depends': ['nhan_su'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/cham_cong.xml',
        'views/dang_ky_lam_viec.xml',
        'views/lich_lam_viec.xml',
        'views/don_xin_den_muon.xml',
        'views/don_xin_ve_som.xml',
        'views/don_xin_nghi.xml',
        'views/don_xin_lam_ngoai_gio_views.xml',
        'views/lich_su_cham_cong.xml',
        'views/thong_ke_cham_cong.xml',
        'views/menus.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
